
import { Language, Product, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  NL: {
    nav_shop: 'Winkel',
    nav_lookbook: 'Lookbook',
    nav_about: 'Over ons',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'De essentie van de straatcultuur.',
    shop_now: 'Nu winkelen',
    est_drop: 'EST. 2024 • DE NIEUWE DROP IS LIVE',
    the_drop: 'DE DROP',
    trending_now: 'Nu trending',
    view_all: 'Bekijk alles',
    add_to_cart: 'In winkelwagen',
    size: 'Maat',
    cart_title: 'Winkelwagen',
    empty_cart: 'Je winkelwagen is leeg.',
    checkout: 'Afrekenen',
    total: 'TOTAAL',
    brand_story: 'Ons Verhaal',
    manifesto_title: 'EEN VERSE BRIES IN DE BETONNEN JUNGLE',
    manifesto_desc: 'STRAATFANAAT is niet zomaar kleding. Het is een bries van moderniteit die als een orkaan de straten raakt. Wij zijn de frisse wind die het stof van de oude mode verdrijft.',
    pillar_auth_title: 'AUTHENTICITEIT',
    pillar_auth_desc: 'Onze wortels liggen op straat. Elk ontwerp is een eerbetoon aan de rauwe, stedelijke realiteit.',
    pillar_innov_title: 'INNOVATIE',
    pillar_innov_desc: 'We combineren technische materialen met futuristische snitten. Mode van de toekomst, vandaag beschikbaar.',
    pillar_comm_title: 'GEMEENSCHAP',
    pillar_comm_desc: 'We zoeken geen klanten, we zoeken fanaten. Sluit je aan bij de beweging die de regels verandert.',
    born_in: 'GEBOREN IN EUROPA. OPGEVOED DOOR DE WERELD.',
    no_boundaries: 'GEEN GRENZEN. GEEN SPIJT.',
    join_family: 'WORD LID VAN DE FAMILIE',
    culture_manifesto_head: "WE DOEN NIET AAN MODE.",
    culture_manifesto_sub: "WE DOEN AAN CULTUUR.",
    join_revolution: "SLUIT JE AAN BIJ DE REVOLUTIE.",
    explore_story: "Ontdek ons verhaal",
    ai_stylist_btn: 'Vraag de AI Stylist',
    ai_stylist_loading: 'De stylist denkt na...',
    ai_stylist_title: 'Straat Advies',
    ai_stylist_prompt: 'Hulp nodig? Vraag het onze AI-expert.',
    admin_lock: 'ADMIN_SLOT',
    admin_dashboard: 'Dashboard',
    admin_inventory: 'Voorraad',
    admin_orders: 'Bestellingen',
    admin_revenue: 'OMZET',
    admin_visitors: 'BEZOEKERS',
    admin_stock: 'VOORRAAD',
    admin_intel: 'STRAAT INTEL',
    admin_add_prod: 'PRODUCT TOEVOEGEN',
    admin_actions: 'ACTIES',
    footer_desc: 'De ultieme bestemming voor straatcultuur en mode. Sluit je aan bij de fanaat-beweging.',
    footer_links: 'LINKS',
    footer_newsletter: 'NIEUWSBRIEF',
    footer_join_btn: 'WORD LID VAN DE STRAAT',
    footer_rights: 'ALLE RECHTEN VOORBEHOUDEN.',
    footer_made_by: 'GEMAAKT DOOR STRAATFANATEN',
  },
  EN: {
    nav_shop: 'Shop',
    nav_lookbook: 'Lookbook',
    nav_about: 'About',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'The essence of street culture.',
    shop_now: 'Shop Now',
    est_drop: 'EST. 2024 • THE NEW DROP IS LIVE',
    the_drop: 'THE DROP',
    trending_now: 'Trending Now',
    view_all: 'View All',
    add_to_cart: 'Add to Cart',
    size: 'Size',
    cart_title: 'Your Cart',
    empty_cart: 'Your cart is empty.',
    checkout: 'Checkout',
    total: 'TOTAL',
    brand_story: 'Our Story',
    manifesto_title: 'A FRESH BREEZE IN THE CONCRETE JUNGLE',
    manifesto_desc: 'STRAATFANAAT is not just clothing. It’s a breeze of modernity that hits the streets with the force of a hurricane. We are the fresh breeze that sweeps away the dust of old fashion.',
    pillar_auth_title: 'AUTHENTICITY',
    pillar_auth_desc: 'Our roots are on the street. Every design is a tribute to raw, urban reality.',
    pillar_innov_title: 'INNOVATION',
    pillar_innov_desc: 'We combine technical materials with futuristic cuts. It is the fashion of the future, available today.',
    pillar_comm_title: 'COMMUNITY',
    pillar_comm_desc: 'We don’t look for customers, we look for fanatics. Join the movement that changes the rules of the game.',
    born_in: 'BORN IN EUROPE. RAISED BY THE WORLD.',
    no_boundaries: 'NO BOUNDARIES. NO REGRETS.',
    join_family: 'JOIN THE FAMILY',
    culture_manifesto_head: "WE DON'T DO FASHION.",
    culture_manifesto_sub: "WE DO CULTURE.",
    join_revolution: "JOIN THE REVOLUTION.",
    explore_story: "Explore our story",
    ai_stylist_btn: 'Ask AI Stylist',
    ai_stylist_loading: 'Stylist is thinking...',
    ai_stylist_title: 'Street Advice',
    ai_stylist_prompt: 'Need tips? Ask our AI expert.',
    admin_lock: 'ADMIN_LOCK',
    admin_dashboard: 'Dashboard',
    admin_inventory: 'Inventory',
    admin_orders: 'Orders',
    admin_revenue: 'REVENUE',
    admin_visitors: 'VISITORS',
    admin_stock: 'STOCK',
    admin_intel: 'STREET INTEL',
    admin_add_prod: 'ADD PRODUCT',
    admin_actions: 'ACTIONS',
    footer_desc: 'The ultimate destination for street culture and fashion. Join the fanatic movement.',
    footer_links: 'LINKS',
    footer_newsletter: 'NEWSLETTER',
    footer_join_btn: 'JOIN THE STREETS',
    footer_rights: 'ALL RIGHTS RESERVED.',
    footer_made_by: 'MADE BY STREET FANATICS',
  },
  PL: {
    nav_shop: 'Sklep',
    nav_lookbook: 'Lookbook',
    nav_about: 'O nas',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'Esencja kultury ulicznej.',
    shop_now: 'Kup Teraz',
    est_drop: 'EST. 2024 • NOWY DROP JEST ONLINE',
    the_drop: 'DROP',
    trending_now: 'Obecnie Trendy',
    view_all: 'Zobacz wszystko',
    add_to_cart: 'Dodaj do Koszyka',
    size: 'Rozmiar',
    cart_title: 'Twój Koszyk',
    empty_cart: 'Twój koszyk jest pusty.',
    checkout: 'Kasa',
    total: 'SUMA',
    brand_story: 'Nasza Historia',
    manifesto_title: 'ŚWIEŻA BRYZA W BETONOWEJ DŻUNGLI',
    manifesto_desc: 'STRAATFANAAT to nie tylko ubrania. To powiew nowoczesności, który uderza w ulice z siłą huraganu. Jesteśmy świeżą bryzą, która przegania kurz starej mody.',
    pillar_auth_title: 'AUTENTYCZNOŚĆ',
    pillar_auth_desc: 'Nasze korzenie są na ulicy. Każdy projekt to hołd dla surowej, miejskiej rzeczywistości.',
    pillar_innov_title: 'INNOWACJA',
    pillar_innov_desc: 'Łączymy techniczne materiały z futurystycznym krojem. To moda przyszłości, dostępna dzisiaj.',
    pillar_comm_title: 'SPOŁECZNOŚĆ',
    pillar_comm_desc: 'Nie szukamy klientów, szukamy fanatyków. Dołącz do ruchu, który zmienia zasady gry.',
    born_in: 'ZRODZENI W EUROPIE. WYCHOWANI PRZEZ ŚWIAT.',
    no_boundaries: 'BEZ GRANIC. BEZ ŻALU.',
    join_family: 'DOŁĄCZ DO RODZINY',
    culture_manifesto_head: "NIE ROBIMY MODY.",
    culture_manifesto_sub: "ROBIMY KULTURĘ.",
    join_revolution: "DOŁĄCZ DO REWOLUCJI.",
    explore_story: "Poznaj naszą historię",
    ai_stylist_btn: 'Zapytaj Stylistę AI',
    ai_stylist_loading: 'Stylista myśli...',
    ai_stylist_title: 'Uliczna Porada',
    ai_stylist_prompt: 'Potrzebujesz rady? Zapytaj naszego Stylistę AI.',
    admin_lock: 'BLOKADA_ADMINA',
    admin_dashboard: 'Pulpit',
    admin_inventory: 'Magazyn',
    admin_orders: 'Zamówienia',
    admin_revenue: 'PRZYCHÓD',
    admin_visitors: 'GOŚCIE',
    admin_stock: 'STAN',
    admin_intel: 'DANE ULICY',
    admin_add_prod: 'DODAJ PRODUKT',
    admin_actions: 'AKCJE',
    footer_desc: 'Ostateczny cel dla kultury ulicznej i mody. Dołącz do ruchu fanatyków.',
    footer_links: 'LINKI',
    footer_newsletter: 'NEWSLETTER',
    footer_join_btn: 'WBIJAJ NA ULICĘ',
    footer_rights: 'WSZELKIE PRAWA ZASTRZEŻONE.',
    footer_made_by: 'STWORZONE PRZEZ ULICZNYCH FANATYKÓW',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'STRAATFANAAT Classic',
    price: 49.99,
    category: 'Tees',
    image: '/images/straatfanaat.jpg',
    images: ['/images/straatfanaat.jpg', '/images/straatfanaat1.jpg', '/images/straatfanaat3.jpeg'],
    description: {
      NL: 'De klassieke STRAATFANAAT tee - pure essentie van straatcultuur. Premium 100% katoen met het iconische logo.',
      EN: 'The classic STRAATFANAAT tee - pure essence of street culture. Premium 100% cotton with iconic logo.',
      PL: 'Klasyczna koszulka STRAATFANAAT - czysta esencja kultury ulicznej. Premium 100% bawełna z kultowym logo.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '2',
    name: 'OMERTA Black Edition',
    price: 54.99,
    category: 'Tees',
    image: '/images/omerta%20(1).jpg',
    images: ['/images/omerta%20(1).jpg', '/images/omerta%20(2).jpg'],
    description: {
      NL: 'De OMERTA collectie - zwijgcode van de straat. Donker design voor echte straatfanaten. Zwijgen is goud.',
      EN: 'The OMERTA collection - code of silence from the streets. Dark design for true street fanatics. Silence is golden.',
      PL: 'Kolekcja OMERTA - kodeks milczenia ulicy. Ciemny design dla prawdziwych ulicznych fanatyków. Milczenie jest złotem.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '3',
    name: 'OMERTA White Edition',
    price: 54.99,
    category: 'Tees',
    image: '/images/bia%C5%82a%20omerta.jpg',
    images: ['/images/bia%C5%82a%20omerta.jpg', '/images/bia%C5%82a%20omerta1.jpg', '/images/bia%C5%82a%20omerta3.jpeg'],
    description: {
      NL: 'OMERTA in zuiver wit - stilte spreekt luider dan woorden. Contrast editie voor de durvers.',
      EN: 'OMERTA in pure white - silence speaks louder than words. Contrast edition for the bold ones.',
      PL: 'OMERTA w czystej bieli - cisza mówi głośniej niż słowa. Kontrastowa edycja dla odważnych.',
    },
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '4',
    name: 'FCDH Black',
    price: 52.99,
    category: 'Tees',
    image: '/images/fcdh%20blak%20(1).jpg',
    images: ['/images/fcdh%20blak%20(1).jpg', '/images/fcdh%20blak%20(2).jpg', '/images/fcdh%20blak3.jpeg'],
    description: {
      NL: 'FCDH - From City, Die Hard. Grafisch meesterwerk met streetwear attitude. Voor de echte straatfanaat.',
      EN: 'FCDH - From City, Die Hard. Graphic masterpiece with streetwear attitude. For the real street fanatic.',
      PL: 'FCDH - From City, Die Hard. Graficzne arcydzieło z ulicznym klimatem. Dla prawdziwego ulicznego fanatyka.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '5',
    name: 'FCDH White',
    price: 52.99,
    category: 'Tees',
    image: '/images/bia%C5%82a%20fcdh%20(1).jpg',
    images: ['/images/bia%C5%82a%20fcdh%20(1).jpg', '/images/bia%C5%82a%20fcdh%20(2).jpg', '/images/bia%C5%82a%20fcdh3.jpeg'],
    description: {
      NL: 'FCDH White Edition - pure energie van de stad in lichte editie. Clean maar agressief.',
      EN: 'FCDH White Edition - pure city energy in light edition. Clean but aggressive streetwear.',
      PL: 'FCDH White Edition - czysta energia miasta w jasnej edycji. Czysty ale agresywny design.',
    },
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '6',
    name: 'BOCIAN Limited Edition',
    price: 59.99,
    category: 'Tees',
    image: '/images/bocian%20(1).jpg',
    images: ['/images/bocian%20(1).jpg', '/images/bocian%20(2).jpg', '/images/bocian3.jpeg'],
    description: {
      NL: 'BOCIAN Limiteerde Editie - Poolse straatcultuur ontmoet internationale stijl. De ooievaar brengt geluk.',
      EN: 'BOCIAN Limited Edition - Polish street culture meets international style. The stork brings luck.',
      PL: 'BOCIAN Limitowana Edycja - polska kultura uliczna spotyka międzynarodowy styl. Bocian przynosi szczęście.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '7',
    name: 'CHAMPION Street',
    price: 57.99,
    category: 'Tees',
    image: '/images/champion.jpg',
    images: ['/images/champion.jpg', '/images/champion2.jpg', '/images/champion3.jpeg'],
    description: {
      NL: 'CHAMPION Street - voor de kampioenen van de straat. Winnaarmentaliteit in premium katoen.',
      EN: 'CHAMPION Street - for the champions of the streets. Winner mentality in premium cotton.',
      PL: 'CHAMPION Street - dla mistrzów ulicy. Mentalność zwycięzcy w premium bawełnie.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
];
