
import { Language, Product, Translation } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  NL: {
    nav_shop: 'Winkel',
    nav_lookbook: 'Lookbook',
    nav_about: 'Over ons',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'De essentie van de straatcultuur.',
    shop_now: 'Nu winkelen',
    est_drop: 'EST. 2024 • DE NIEUWE DROP IS LIVE',
    the_drop: 'DE DROP',
    trending_now: 'Nu trending',
    view_all: 'Bekijk alles',
    add_to_cart: 'In winkelwagen',
    size: 'Maat',
    cart_title: 'Winkelwagen',
    empty_cart: 'Je winkelwagen is leeg.',
    checkout: 'Afrekenen',
    total: 'TOTAAL',
    brand_story: 'Ons Verhaal',
    manifesto_title: 'EEN VERSE BRIES IN DE BETONNEN JUNGLE',
    manifesto_desc: 'STRAATFANAAT is niet zomaar kleding. Het is een bries van moderniteit die als een orkaan de straten raakt. Wij zijn de frisse wind die het stof van de oude mode verdrijft.',
    pillar_auth_title: 'AUTHENTICITEIT',
    pillar_auth_desc: 'Onze wortels liggen op straat. Elk ontwerp is een eerbetoon aan de rauwe, stedelijke realiteit.',
    pillar_innov_title: 'INNOVATIE',
    pillar_innov_desc: 'We combineren technische materialen met futuristische snitten. Mode van de toekomst, vandaag beschikbaar.',
    pillar_comm_title: 'GEMEENSCHAP',
    pillar_comm_desc: 'We zoeken geen klanten, we zoeken fanaten. Sluit je aan bij de beweging die de regels verandert.',
    born_in: 'GEBOREN IN EUROPA. OPGEVOED DOOR DE WERELD.',
    no_boundaries: 'GEEN GRENZEN. GEEN SPIJT.',
    join_family: 'WORD LID VAN DE FAMILIE',
    culture_manifesto_head: "WE DOEN NIET AAN MODE.",
    culture_manifesto_sub: "WE DOEN AAN CULTUUR.",
    join_revolution: "SLUIT JE AAN BIJ DE REVOLUTIE.",
    explore_story: "Ontdek ons verhaal",
    ai_stylist_btn: 'Vraag de AI Stylist',
    ai_stylist_loading: 'De stylist denkt na...',
    ai_stylist_title: 'Straat Advies',
    ai_stylist_prompt: 'Hulp nodig? Vraag het onze AI-expert.',
    admin_lock: 'ADMIN_SLOT',
    admin_dashboard: 'Dashboard',
    admin_inventory: 'Voorraad',
    admin_orders: 'Bestellingen',
    admin_revenue: 'OMZET',
    admin_visitors: 'BEZOEKERS',
    admin_stock: 'VOORRAAD',
    admin_intel: 'STRAAT INTEL',
    admin_add_prod: 'PRODUCT TOEVOEGEN',
    admin_actions: 'ACTIES',
    footer_desc: 'De ultieme bestemming voor straatcultuur en mode. Sluit je aan bij de fanaat-beweging.',
    footer_links: 'LINKS',
    footer_newsletter: 'NIEUWSBRIEF',
    footer_join_btn: 'WORD LID VAN DE STRAAT',
    footer_rights: 'ALLE RECHTEN VOORBEHOUDEN.',
    footer_made_by: 'GEMAAKT DOOR STRAATFANATEN',
  },
  EN: {
    nav_shop: 'Shop',
    nav_lookbook: 'Lookbook',
    nav_about: 'About',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'The essence of street culture.',
    shop_now: 'Shop Now',
    est_drop: 'EST. 2024 • THE NEW DROP IS LIVE',
    the_drop: 'THE DROP',
    trending_now: 'Trending Now',
    view_all: 'View All',
    add_to_cart: 'Add to Cart',
    size: 'Size',
    cart_title: 'Your Cart',
    empty_cart: 'Your cart is empty.',
    checkout: 'Checkout',
    total: 'TOTAL',
    brand_story: 'Our Story',
    manifesto_title: 'A FRESH BREEZE IN THE CONCRETE JUNGLE',
    manifesto_desc: 'STRAATFANAAT is not just clothing. It’s a breeze of modernity that hits the streets with the force of a hurricane. We are the fresh breeze that sweeps away the dust of old fashion.',
    pillar_auth_title: 'AUTHENTICITY',
    pillar_auth_desc: 'Our roots are on the street. Every design is a tribute to raw, urban reality.',
    pillar_innov_title: 'INNOVATION',
    pillar_innov_desc: 'We combine technical materials with futuristic cuts. It is the fashion of the future, available today.',
    pillar_comm_title: 'COMMUNITY',
    pillar_comm_desc: 'We don’t look for customers, we look for fanatics. Join the movement that changes the rules of the game.',
    born_in: 'BORN IN EUROPE. RAISED BY THE WORLD.',
    no_boundaries: 'NO BOUNDARIES. NO REGRETS.',
    join_family: 'JOIN THE FAMILY',
    culture_manifesto_head: "WE DON'T DO FASHION.",
    culture_manifesto_sub: "WE DO CULTURE.",
    join_revolution: "JOIN THE REVOLUTION.",
    explore_story: "Explore our story",
    ai_stylist_btn: 'Ask AI Stylist',
    ai_stylist_loading: 'Stylist is thinking...',
    ai_stylist_title: 'Street Advice',
    ai_stylist_prompt: 'Need tips? Ask our AI expert.',
    admin_lock: 'ADMIN_LOCK',
    admin_dashboard: 'Dashboard',
    admin_inventory: 'Inventory',
    admin_orders: 'Orders',
    admin_revenue: 'REVENUE',
    admin_visitors: 'VISITORS',
    admin_stock: 'STOCK',
    admin_intel: 'STREET INTEL',
    admin_add_prod: 'ADD PRODUCT',
    admin_actions: 'ACTIONS',
    footer_desc: 'The ultimate destination for street culture and fashion. Join the fanatic movement.',
    footer_links: 'LINKS',
    footer_newsletter: 'NEWSLETTER',
    footer_join_btn: 'JOIN THE STREETS',
    footer_rights: 'ALL RIGHTS RESERVED.',
    footer_made_by: 'MADE BY STREET FANATICS',
  },
  PL: {
    nav_shop: 'Sklep',
    nav_lookbook: 'Lookbook',
    nav_about: 'O nas',
    hero_title: 'STRAATFANAAT',
    hero_subtitle: 'Esencja kultury ulicznej.',
    shop_now: 'Kup Teraz',
    est_drop: 'EST. 2024 • NOWY DROP JEST ONLINE',
    the_drop: 'DROP',
    trending_now: 'Obecnie Trendy',
    view_all: 'Zobacz wszystko',
    add_to_cart: 'Dodaj do Koszyka',
    size: 'Rozmiar',
    cart_title: 'Twój Koszyk',
    empty_cart: 'Twój koszyk jest pusty.',
    checkout: 'Kasa',
    total: 'SUMA',
    brand_story: 'Nasza Historia',
    manifesto_title: 'ŚWIEŻA BRYZA W BETONOWEJ DŻUNGLI',
    manifesto_desc: 'STRAATFANAAT to nie tylko ubrania. To powiew nowoczesności, który uderza w ulice z siłą huraganu. Jesteśmy świeżą bryzą, która przegania kurz starej mody.',
    pillar_auth_title: 'AUTENTYCZNOŚĆ',
    pillar_auth_desc: 'Nasze korzenie są na ulicy. Każdy projekt to hołd dla surowej, miejskiej rzeczywistości.',
    pillar_innov_title: 'INNOWACJA',
    pillar_innov_desc: 'Łączymy techniczne materiały z futurystycznym krojem. To moda przyszłości, dostępna dzisiaj.',
    pillar_comm_title: 'SPOŁECZNOŚĆ',
    pillar_comm_desc: 'Nie szukamy klientów, szukamy fanatyków. Dołącz do ruchu, który zmienia zasady gry.',
    born_in: 'ZRODZENI W EUROPIE. WYCHOWANI PRZEZ ŚWIAT.',
    no_boundaries: 'BEZ GRANIC. BEZ ŻALU.',
    join_family: 'DOŁĄCZ DO RODZINY',
    culture_manifesto_head: "NIE ROBIMY MODY.",
    culture_manifesto_sub: "ROBIMY KULTURĘ.",
    join_revolution: "DOŁĄCZ DO REWOLUCJI.",
    explore_story: "Poznaj naszą historię",
    ai_stylist_btn: 'Zapytaj Stylistę AI',
    ai_stylist_loading: 'Stylista myśli...',
    ai_stylist_title: 'Uliczna Porada',
    ai_stylist_prompt: 'Potrzebujesz rady? Zapytaj naszego Stylistę AI.',
    admin_lock: 'BLOKADA_ADMINA',
    admin_dashboard: 'Pulpit',
    admin_inventory: 'Magazyn',
    admin_orders: 'Zamówienia',
    admin_revenue: 'PRZYCHÓD',
    admin_visitors: 'GOŚCIE',
    admin_stock: 'STAN',
    admin_intel: 'DANE ULICY',
    admin_add_prod: 'DODAJ PRODUKT',
    admin_actions: 'AKCJE',
    footer_desc: 'Ostateczny cel dla kultury ulicznej i mody. Dołącz do ruchu fanatyków.',
    footer_links: 'LINKI',
    footer_newsletter: 'NEWSLETTER',
    footer_join_btn: 'WBIJAJ NA ULICĘ',
    footer_rights: 'WSZELKIE PRAWA ZASTRZEŻONE.',
    footer_made_by: 'STWORZONE PRZEZ ULICZNYCH FANATYKÓW',
  },
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'STRAATFANAAT Classic',
    price: 49.99,
    category: 'Tees',
    image: '/images/straatfanaat.jpg',
    images: ['/images/straatfanaat.jpg', '/images/straatfanaat1.jpg', '/images/straatfanaat3.jpeg'],
    previewImages: ['/images/straatfanaat4%20podglad.jpeg', '/images/straatfanaat5%20podglad.jpeg'],
    description: {
      NL: 'De klassieke STRAATFANAAT tee - pure essentie van straatcultuur. Premium 100% katoen met het iconische logo. Oversized fit voor ultiem comfort en authentieke streetwear look.',
      EN: 'The classic STRAATFANAAT tee - pure essence of street culture. Premium 100% cotton with iconic logo. Oversized fit for ultimate comfort and authentic streetwear look.',
      PL: 'Klasyczna koszulka STRAATFANAAT - czysta esencja kultury ulicznej. Premium 100% bawełna z kultowym logo. Oversize krój dla maksymalnego komfortu i autentycznego streetwear look.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '2',
    name: 'OMERTA Black Edition',
    price: 54.99,
    category: 'Tees',
    image: '/images/omerta%20(1).jpg',
    images: ['/images/omerta%20(1).jpg', '/images/omerta%20(2).jpg'],
    previewImages: ['/images/omerta%203%20podglad.jpeg', '/images/omerta4%20podglad%20.jpeg'],
    description: {
      NL: 'De OMERTA collectie - zwijgcode van de straat. Donker design voor echte straatfanaten. Zwijgen is goud. Premium 300gsm katoen met intense grafiek.',
      EN: 'The OMERTA collection - code of silence from the streets. Dark design for true street fanatics. Silence is golden. Premium 300gsm cotton with intense graphics.',
      PL: 'Kolekcja OMERTA - kodeks milczenia ulicy. Ciemny design dla prawdziwych ulicznych fanatyków. Milczenie jest złotem. Premium bawełna 300gsm z intensywną grafiką.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '3',
    name: 'OMERTA White Edition',
    price: 54.99,
    category: 'Tees',
    image: '/images/bia%C5%82a%20omerta.jpg',
    images: ['/images/bia%C5%82a%20omerta.jpg', '/images/bia%C5%82a%20omerta1.jpg', '/images/bia%C5%82a%20omerta3.jpeg'],
    previewImages: ['/images/bia%C5%82a%20omerta4%20podglad.jpeg', '/images/bia%C5%82a%20omerta5%20podglad.jpeg'],
    description: {
      NL: 'OMERTA in zuiver wit - stilte spreekt luider dan woorden. Contrast editie voor de durvers. Premium katoen met gedurfde grafiek die opvalt in elke menigte.',
      EN: 'OMERTA in pure white - silence speaks louder than words. Contrast edition for the bold ones. Premium cotton with daring graphics that stand out in any crowd.',
      PL: 'OMERTA w czystej bieli - cisza mówi głośniej niż słowa. Kontrastowa edycja dla odważnych. Premium bawełna z odważną grafiką, która wyróżnia się w każdym tłumie.',
    },
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '4',
    name: 'FCDH Black',
    price: 52.99,
    category: 'Tees',
    image: '/images/fcdh%20blak%20(1).jpg',
    images: ['/images/fcdh%20blak%20(1).jpg', '/images/fcdh%20blak%20(2).jpg', '/images/fcdh%20blak3.jpeg'],
    previewImages: [],
    description: {
      NL: 'FCDH - From City, Die Hard. Grafisch meesterwerk met streetwear attitude. Voor de echte straatfanaat. Oversized fit, premium druk die niet vervaagt.',
      EN: 'FCDH - From City, Die Hard. Graphic masterpiece with streetwear attitude. For the real street fanatic. Oversized fit, premium print that never fades.',
      PL: 'FCDH - From City, Die Hard. Graficzne arcydzieło z ulicznym klimatem. Dla prawdziwego ulicznego fanatyka. Oversize krój, premium nadruk, który nie blaknie.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '5',
    name: 'FCDH White',
    price: 52.99,
    category: 'Tees',
    image: '/images/bia%C5%82a%20fcdh%20(1).jpg',
    images: ['/images/bia%C5%82a%20fcdh%20(1).jpg', '/images/bia%C5%82a%20fcdh%20(2).jpg', '/images/bia%C5%82a%20fcdh3.jpeg'],
    previewImages: ['/images/bia%C5%82a%20fcdh4%20podglad.jpeg', '/images/bia%C5%82a%20fcdh5%20podglad.jpeg'],
    description: {
      NL: 'FCDH White Edition - pure energie van de stad in lichte editie. Clean maar agressief. Premium katoen die ademt en comfortabel zit de hele dag.',
      EN: 'FCDH White Edition - pure city energy in light edition. Clean but aggressive streetwear. Premium cotton that breathes and stays comfortable all day.',
      PL: 'FCDH White Edition - czysta energia miasta w jasnej edycji. Czysty ale agresywny design. Premium bawełna, która oddycha i jest wygodna przez cały dzień.',
    },
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '6',
    name: 'BOCIAN Limited Edition',
    price: 59.99,
    category: 'Tees',
    image: '/images/bocian%20(1).jpg',
    images: ['/images/bocian%20(1).jpg', '/images/bocian%20(2).jpg', '/images/bocian3.jpeg'],
    previewImages: ['/images/bocian4%20podglad.jpeg', '/images/bocian5%20podglad.jpeg'],
    description: {
      NL: 'BOCIAN Limiteerde Editie - Poolse straatcultuur ontmoet internationale stijl. De ooievaar brengt geluk. Exclusief ontwerp met symboliek die diep in de Slavische cultuur geworteld is.',
      EN: 'BOCIAN Limited Edition - Polish street culture meets international style. The stork brings luck. Exclusive design with symbolism deeply rooted in Slavic culture.',
      PL: 'BOCIAN Limitowana Edycja - polska kultura uliczna spotyka międzynarodowy styl. Bocian przynosi szczęście. Ekskluzywny design z symboliką głęboko zakorzenioną w słowiańskiej kulturze.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '7',
    name: 'CHAMPION Street',
    price: 57.99,
    category: 'Tees',
    image: '/images/champion.jpg',
    images: ['/images/champion.jpg', '/images/champion2.jpg', '/images/champion3.jpeg'],
    previewImages: ['/images/champion4%20podglad.jpeg', '/images/champion5%20podglad.jpeg'],
    description: {
      NL: 'CHAMPION Street - voor de kampioenen van de straat. Winnaarmentaliteit in premium katoen. Oversized fit met ultra-gedetailleerde print.',
      EN: 'CHAMPION Street - for the champions of the streets. Winner mentality in premium cotton. Oversized fit with ultra-detailed print.',
      PL: 'CHAMPION Street - dla mistrzów ulicy. Mentalność zwycięzcy w premium bawełnie. Oversize krój z ultra-detalicznym nadrukiem.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '8',
    name: 'SAVAGE OMERTA',
    price: 59.99,
    category: 'Tees',
    image: '/images/savage%20omerta.jpeg',
    images: ['/images/savage%20omerta.jpeg', '/images/savage%20omerta1.jpeg', '/images/savage%20omerta4.jpeg'],
    previewImages: ['/images/savage%20omerta2%20podglad.jpeg', '/images/savage%20omerta3%20podglad.jpeg'],
    description: {
      NL: 'SAVAGE OMERTA - De meest agressieve editie van de OMERTA-lijn. Wanneer stilte dodelijk wordt. Premium 300gsm katoen met explosieve grafiek die de essentie van straatcultuur vastlegt. Geen compromissen, geen excuses.',
      EN: 'SAVAGE OMERTA - The most aggressive edition of the OMERTA line. When silence becomes deadly. Premium 300gsm cotton with explosive graphics capturing the essence of street culture. No compromises, no excuses.',
      PL: 'SAVAGE OMERTA - Najbardziej agresywna edycja linii OMERTA. Kiedy cisza staje się śmiertelna. Premium bawełna 300gsm z eksplozywną grafiką oddającą esencję kultury ulicznej. Bez kompromisów, bez wymówek.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '9',
    name: 'STRAATFANAAT MUZEUM',
    price: 64.99,
    category: 'Tees',
    image: '/images/straatfanaat%20muzeum2.jpeg',
    images: ['/images/straatfanaat%20muzeum2.jpeg'],
    previewImages: ['/images/straatfanaat%20muzeum%20podglad.jpeg', '/images/straatfanaat%20muzeum1%20podglad.jpeg'],
    description: {
      NL: 'STRAATFANAAT MUZEUM - Waar streetwear kunst wordt. Een eerbetoon aan de geschiedenis van straatcultuur, vastgelegd in een tijdloos ontwerp. Museum-kwaliteit print op premium katoen. Draag de erfenis.',
      EN: 'STRAATFANAAT MUSEUM - Where streetwear becomes art. A tribute to the history of street culture, captured in a timeless design. Museum-quality print on premium cotton. Wear the legacy.',
      PL: 'STRAATFANAAT MUZEUM - Gdzie streetwear staje się sztuką. Hołd dla historii kultury ulicznej, uchwycony w ponadczasowym designie. Muzealnej jakości nadruk na premium bawełnie. Noś dziedzictwo.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '10',
    name: 'STRAATFANAAT STRIT',
    price: 54.99,
    category: 'Tees',
    image: '/images/straatfanaat%20strit1.jpeg',
    images: ['/images/straatfanaat%20strit1.jpeg'],
    previewImages: ['/images/straatfanaat%20strit%20podglad.jpeg'],
    description: {
      NL: 'STRAATFANAAT STRIT - De pure essentie van het straatleven. Rauwe energie van de betonnen jungle gevangen in een iconisch ontwerp. Deze tee schreeuwt authenticiteit. 100% straatcredibiliteit.',
      EN: 'STRAATFANAAT STRIT - The pure essence of street life. Raw energy from the concrete jungle captured in an iconic design. This tee screams authenticity. 100% street credibility.',
      PL: 'STRAATFANAAT STRIT - Czysta esencja życia ulicznego. Surowa energia betonowej dżungli uchwycona w kultowym designie. Ta koszulka krzyczy autentyczność. 100% uliczna wiarygodność.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '11',
    name: 'HERB Street Edition',
    price: 52.99,
    category: 'Tees',
    image: '/images/herb1.jpeg',
    images: ['/images/herb1.jpeg'],
    previewImages: ['/images/herb%20podglad.jpeg'],
    description: {
      NL: 'HERB Street Edition - Natuur ontmoet de stad. Organische vibes versmolten met stedelijke hardheid. Een unieke fusie die je onderscheidt van de massa. Groene roots, straatmentaliteit.',
      EN: 'HERB Street Edition - Nature meets the city. Organic vibes fused with urban hardness. A unique fusion that sets you apart from the crowd. Green roots, street mentality.',
      PL: 'HERB Street Edition - Natura spotyka miasto. Organiczne wibracje połączone z miejską twardością. Unikalna fuzja, która wyróżnia cię z tłumu. Zielone korzenie, uliczna mentalność.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '12',
    name: 'DH MIASTO',
    price: 54.99,
    category: 'Tees',
    image: '/images/DH%20miasto%20podglad.jpeg',
    images: ['/images/DH%20miasto%20podglad.jpeg'],
    previewImages: ['/images/DH%20miasto%20podglad.jpeg'],
    description: {
      NL: 'DH MIASTO - De stad is ons thuis. Die Hard stadsguerilla met Poolse roots. Een statement voor iedereen die de betonnen jungle als hun natuurlijke habitat beschouwt.',
      EN: 'DH MIASTO - The city is our home. Die Hard urban guerrilla with Polish roots. A statement for everyone who considers the concrete jungle their natural habitat.',
      PL: 'DH MIASTO - Miasto to nasz dom. Die Hard miejska guerilla z polskimi korzeniami. Statement dla każdego, kto betonową dżunglę uważa za swoje naturalne środowisko.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: '13',
    name: 'FCDH PINK DAMSKA',
    price: 52.99,
    category: 'Damskie',
    image: '/images/damska%20fcdh%20r%C3%B3zowy%201.jpeg',
    images: ['/images/damska%20fcdh%20r%C3%B3zowy%201.jpeg'],
    previewImages: ['/images/damska%20fcdh%20r%C3%B3zowy%20%20podglad.jpeg'],
    description: {
      NL: 'FCDH PINK DAMSKA - De vrouwelijke versie van onze iconische FCDH-lijn. Roze power ontmoet straatmentaliteit. Fitted cut speciaal ontworpen voor vrouwen die de straat domineren. From City, Die Hard - geen genderregels.',
      EN: 'FCDH PINK DAMSKA - The feminine version of our iconic FCDH line. Pink power meets street mentality. Fitted cut specially designed for women who dominate the streets. From City, Die Hard - no gender rules.',
      PL: 'FCDH PINK DAMSKA - Damska wersja naszej kultowej linii FCDH. Różowa siła spotyka uliczną mentalność. Dopasowany krój specjalnie zaprojektowany dla kobiet, które dominują ulice. From City, Die Hard - bez zasad płci.',
    },
    colors: ['Pink'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '14',
    name: 'KOLEKCJA DLA NIEJ',
    price: 54.99,
    category: 'Damskie',
    image: '/images/kolekcja%20dla%20niej%20dla%20niego%20damska%20.jpeg',
    images: ['/images/kolekcja%20dla%20niej%20dla%20niego%20damska%20.jpeg'],
    previewImages: ['/images/kolekcja%20dla%20niej%20dla%20niego%20damska%20podglad%20.jpeg', '/images/kolekcja%20dla%20niego%20dla%20niej%20damska%20%20podglad.jpeg'],
    description: {
      NL: 'KOLEKCJA DLA NIEJ - Streetwear voor de sterke vrouw. Een exclusieve lijn die de grenzen van gendermode doorbreekt. Premium materialen, vrouwelijke snit, ongecompromitteerde straatattitude. Voor haar die niet vraagt om aandacht - ze eist het.',
      EN: 'KOLEKCJA DLA NIEJ - Streetwear for the strong woman. An exclusive line that breaks the boundaries of gender fashion. Premium materials, feminine cut, uncompromised street attitude. For her who doesnt ask for attention - she demands it.',
      PL: 'KOLEKCJA DLA NIEJ - Streetwear dla silnej kobiety. Ekskluzywna linia, która przełamuje granice mody genderowej. Premium materiały, kobiecy krój, bezkompromisowa uliczna postawa. Dla tej, która nie prosi o uwagę - ona ją wymusza.',
    },
    colors: ['Black', 'White'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    id: '15',
    name: 'KOLEKCJA DLA NIEGO',
    price: 54.99,
    category: 'Tees',
    image: '/images/kolekcja%20dla%20niego%20dla%20niej%20sesia%20.jpeg',
    images: ['/images/kolekcja%20dla%20niego%20dla%20niej%20sesia%20.jpeg', '/images/kolekcja%20dla%20niego%20dla%20niej%20sesia1.jpeg', '/images/kolekcja%20dla%20niego%20dla%20niej%20sesia2.jpeg'],
    previewImages: ['/images/kolekcja%20dla%20niego%20dla%20niej%20meska%201%20podglad.jpeg', '/images/kolekcja%20dla%20niej%20dla%20niego%20meska%20podglad%20.jpeg'],
    description: {
      NL: 'KOLEKCJA DLA NIEGO - De mannelijke tegenhanger van onze duo-collectie. Ontworpen voor degenen die weten wat ze willen. Oversized fit, premium 300gsm katoen, iconische grafiek. Match met haar of maak je eigen statement.',
      EN: 'KOLEKCJA DLA NIEGO - The masculine counterpart of our duo collection. Designed for those who know what they want. Oversized fit, premium 300gsm cotton, iconic graphics. Match with her or make your own statement.',
      PL: 'KOLEKCJA DLA NIEGO - Męski odpowiednik naszej kolekcji duo. Zaprojektowana dla tych, którzy wiedzą czego chcą. Oversize krój, premium bawełna 300gsm, kultowa grafika. Dopasuj się do niej lub stwórz własny statement.',
    },
    colors: ['Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
];
